### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by intgr** [DavisRayM/django-filter-stubs#8]
The issue fixed in #2 sometimes reappears.

**Comment by intgr** [comment]
@DavisRayM Ping.

**Comment by DavisRayM** [comment]
Hey @intgr. I'll make a release for this later today

**Comment by DavisRayM** [comment]
A new release has been tagged. Added a github workflow to make this easier in the future.

**Comment by sshishov** [comment]
Can this repo relocate under https://github.com/python/typeshed
Then you guys will have a community to add type hints for it
